# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qv14cq7WCidd_x8Tve5p3w118kxaLphM
"""

from flask import Flask, request, jsonify
import torch
import torch.nn as nn
from torchvision.models import efficientnet_b0
import torchvision.transforms as transforms
from PIL import Image
import os

app = Flask(__name__)

# Liste des classes dans l'ordre
class_names = [
    'yorkshire_terrier', 'Siamese', 'samoyed', 'scottish_terrier', 'Russian_Blue',
    'shiba_inu', 'staffordshire_bull_terrier', 'wheaten_terrier', 'Sphynx', 'saint_bernard',
    'pug', 'Maine_Coon', 'Persian', 'pomeranian', 'japanese_chin', 'miniature_pinscher',
    'newfoundland', 'keeshond', 'Ragdoll', 'leonberger', 'great_pyrenees', 'Bombay',
    'german_shorthaired', 'havanese', 'chihuahua', 'boxer', 'British_Shorthair',
    'english_setter', 'english_cocker_spaniel', 'Egyptian_Mau', 'american_bulldog',
    'beagle', 'Bengal', 'basset_hound', 'Birman', 'Abyssinian', 'american_pit_bull_terrier'
]

# Transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Charger le modèle une seule fois
def load_model():
    model = efficientnet_b0(pretrained=False)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, len(class_names))
    model.load_state_dict(torch.load("best_model (1).pth", map_location=torch.device("cpu")))
    model.eval()
    return model

model = load_model()

# Route d'accueil
@app.route('/')
def home():
    return "API de prédiction - Classification de races d'animaux 🐶🐱"

# Route de prédiction
@app.route('/predict', methods=['POST'])
def predict():
    if 'image' not in request.files:
        return jsonify({'error': 'Aucune image trouvée'}), 400

    image_file = request.files['image']
    image = Image.open(image_file).convert("RGB")
    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)
        prediction = class_names[predicted.item()]

    return jsonify({'prediction': prediction})

if __name__ == '__main__':
    app.run(debug=True)