# -*- coding: utf-8 -*-
"""classif_git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4OnPRpZdCY3WO-a0oJ9FDJx5ABkfWnl
"""

from flask import Flask, request, jsonify
from PIL import Image
import torch
from torchvision import transforms
import json
from torchvision.models import efficientnet_b0 # Import the model architecture
import torch.nn as nn
app = Flask(__name__)

# Charger le modèle
# 1. Create an instance of the model
model = efficientnet_b0(pretrained=False)
# Before loading the weights, modify the classifier layer to match the saved model
nb_classes = 37 # Replace 37 with the actual number of classes in your saved model
num_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_features, nb_classes)

# 2. Load the state_dict into the model instance
model.load_state_dict(torch.load("best_model (1).pth", map_location=torch.device('cpu')))
model.eval()

# Charger les classes
with open("class_labels.json", "r") as f:
    class_map = json.load(f)
idx_to_class = {v: k for k, v in class_map.items()}

# Prétraitement
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

@app.route("/predict", methods=["POST"])
def predict():
    if 'file' not in request.files:
        return jsonify({"error": "No file provided"}), 400

    file = request.files["file"]
    image = Image.open(file).convert("RGB")
    input_tensor = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = model(input_tensor)
        _, predicted = outputs.max(1)
        class_name = idx_to_class[predicted.item()]

    return jsonify({"prediction": class_name})

if __name__ == "__main__":
    app.run(debug=True)